name: Visium Quality Control

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  r-visum-qc:
    runs-on: ubuntu-noble

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv  # persistent cache location

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for R packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
        shell: bash

      - name: Cache R packages (renv)
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Set repositories
        run: Rscript ubuntu.R

      - name: Restore environment from renv.lock
        run: |
          install.packages("renv", repos = "https://cloud.r-project.org")
          renv::restore(prompt = FALSE)
        shell: Rscript {0}

      - name: Get data
        run: Rscript visium/download-test-data.R

      - name: Run visium quality assessment
        run: Rscript visium/01_quality_assessment/quality_assessment.qmd
